In [1]:
import os
import time
import pickle
import itertools
import numpy as np
import pandas as pd
import lightgbm as lgb
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from utilities import *

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lightgbm/__init__.py:45: FutureWarning: Starting from version 2.2.1, the library file in distribution wheels for macOS will be built by the Apple Clang compiler.
This means that in case of installing LightGBM from PyPI via the ``pip install lightgbm`` command, you won't need to install the gcc compiler anymore.
Instead of that, you'll need to install the OpenMP library, which is required for running LightGBM on the system with the Apple Clang compiler.
You can install the OpenMP library by the following command: ``brew install libomp``.
  "You can install the OpenMP library by the following command: ``brew install libomp``.", FutureWarning)

In [2]:
stack_idx = '14'
models = '1-22'
use_test_kfold = set([2, 7, 8, 12, 13])

is_per_area = True

In [3]:
model_name = 'stack_lgb_'+stack_idx+'-1'

### Read CV predictions and test

In [4]:
def parse_models(exp):
    exp_split = exp.split(',')
    idx_models = []
    for e in exp_split:
        if '-' in e:
            n0, n1 = e.split('-')
            idx_models.extend(list(range(int(n0), int(n1)+1, 1)))
        else:
            idx_models.append(int(e))
    return idx_models

In [5]:
idx_models = parse_models(models)
print(idx_models)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

In [6]:
files_in_output = [f for f in os.listdir('output/') if os.path.isfile('output/'+f)]
files_cv = {idx: [f for f in files_in_output 
                  if f.startswith('model-%02d-' % idx) and f.endswith('cv.csv')][0] 
            for idx in idx_models}
files_test_one = {idx: [f for f in files_in_output 
                        if f.startswith('model-%02d-' % idx) and f.endswith('test-one.csv')][0]
                  for idx in idx_models}
files_test_kf = {idx: [f for f in files_in_output 
                       if f.startswith('model-%02d-' % idx) and f.endswith('test-kfold.csv')][0]
                 for idx in idx_models}

In [7]:
for k in files_cv: 
    print('%2d'%k, files_cv[k])
    print('%2d'%k, files_test_kf[k])
    print('%2d'%k, files_test_one[k])

 1 model-01-lgb-cv.csv
 1 model-01-lgb-test-kfold.csv
 1 model-01-lgb-test-one.csv
 2 model-02-keras-search-cv.csv
 2 model-02-keras-search-test-kfold.csv
 2 model-02-keras-search-test-one.csv
 3 model-03-lgb-feats-selection-cv.csv
 3 model-03-lgb-feats-selection-test-kfold.csv
 3 model-03-lgb-feats-selection-test-one.csv
 4 model-04-lgb-PCA-cv.csv
 4 model-04-lgb-PCA-test-kfold.csv
 4 model-04-lgb-PCA-test-one.csv
 5 model-05-lgb-wo-per-area-cv.csv
 5 model-05-lgb-wo-per-area-test-kfold.csv
 5 model-05-lgb-wo-per-area-test-one.csv
 6 model-06-lgb-lr0.001-cv.csv
 6 model-06-lgb-lr0.001-test-kfold.csv
 6 model-06-lgb-lr0.001-test-one.csv
 7 model-07-keras-embedding-cv.csv
 7 model-07-keras-embedding-test-kfold.csv
 7 model-07-keras-embedding-test-one.csv
 8 model-08-keras-search-long-cv.csv
 8 model-08-keras-search-long-test-kfold.csv
 8 model-08-keras-search-long-test-one.csv
 9 model-09-lgb-feats-selection-75-cv.csv
 9 model-09-lgb-feats-selection-75-test-kfold.csv
 9 model-09-lgb-feats-selection-75-test-one.csv
10 model-10-lgb-feats-selection-75-lr-0.001-cv.csv
10 model-10-lgb-feats-selection-75-lr-0.001-test-kfold.csv
10 model-10-lgb-feats-selection-75-lr-0.001-test-one.csv
11 model-11-rf-cv.csv
11 model-11-rf-test-kfold.csv
11 model-11-rf-test-one.csv
12 model-12-predict-keras-search-prelu-cv.csv
12 model-12-predict-keras-search-prelu-test-kfold.csv
12 model-12-predict-keras-search-prelu-test-one.csv
13 model-13-predict-keras-he_uni-cv.csv
13 model-13-predict-keras-he_uni-test-kfold.csv
13 model-13-predict-keras-he_uni-test-one.csv
14 model-14-lgb-feats-selection-75-lr-0.001-rand-cv.csv
14 model-14-lgb-feats-selection-75-lr-0.001-rand-test-kfold.csv
14 model-14-lgb-feats-selection-75-lr-0.001-rand-test-one.csv
15 model-15-lgb-feats-selection-75-lr-0.001-rand323-cv.csv
15 model-15-lgb-feats-selection-75-lr-0.001-rand323-test-kfold.csv
15 model-15-lgb-feats-selection-75-lr-0.001-rand323-test-one.csv
16 model-16-lgb-feats-selection-68-lr-0.001-mix5-cv.csv
16 model-16-lgb-feats-selection-68-lr-0.001-mix5-test-kfold.csv
16 model-16-lgb-feats-selection-68-lr-0.001-mix5-test-one.csv
17 model-17-lgb-feats-selection-70-lr-0.001-mix5-cv.csv
17 model-17-lgb-feats-selection-70-lr-0.001-mix5-test-kfold.csv
17 model-17-lgb-feats-selection-70-lr-0.001-mix5-test-one.csv
18 model-18-lgb-feats-selection-70-lr-0.001-p5-cv.csv
18 model-18-lgb-feats-selection-70-lr-0.001-p5-test-kfold.csv
18 model-18-lgb-feats-selection-70-lr-0.001-p5-test-one.csv
19 model-19-lgb-search-bins-lr-0.0005-cv.csv
19 model-19-lgb-search-bins-lr-0.0005-test-kfold.csv
19 model-19-lgb-search-bins-lr-0.0005-test-one.csv
20 model-20-lgb-lr-0.0008-mix5-cv.csv
20 model-20-lgb-lr-0.0008-mix5-test-kfold.csv
20 model-20-lgb-lr-0.0008-mix5-test-one.csv
21 model-21-lgb-wo-per-area-long-cv.csv
21 model-21-lgb-wo-per-area-long-test-kfold.csv
21 model-21-lgb-wo-per-area-long-test-one.csv
22 model-22-lgb-wo-per-area-long-2-cv.csv
22 model-22-lgb-wo-per-area-long-2-test-kfold.csv
22 model-22-lgb-wo-per-area-long-2-test-one.csv

#### Load area

In [8]:
df_train = pd.read_csv('dataset/train.csv')
df_test = pd.read_csv('dataset/test.csv')

In [9]:
cv = df_train[['building_id', 'building_area', 'total_price']]
test_pred = df_test[['building_id', 'building_area']]

In [10]:
print('CV predictions:')
for i, idx_model in enumerate(idx_models):
    f = files_cv[idx_model]
    print('No. {} file: {}'.format(i, f))
    df = pd.read_csv('output/'+f)
    
    cv = pd.merge(cv, df[['building_id', 'total_price_predict']], on='building_id')
    
    cv = cv.rename(columns = {'total_price_predict': 'pred_{}'.format(idx_model)})
    cv[f'log_pred_{idx_model}'] = np.log1p(cv[f'pred_{idx_model}'])
    cv[f'log_parea_pred_{idx_model}'] = np.log1p( cv[f'pred_{idx_model}'] / cv['building_area'] )

CV predictions:
No. 0 file: model-01-lgb-cv.csv
No. 1 file: model-02-keras-search-cv.csv
No. 2 file: model-03-lgb-feats-selection-cv.csv
No. 3 file: model-04-lgb-PCA-cv.csv
No. 4 file: model-05-lgb-wo-per-area-cv.csv
No. 5 file: model-06-lgb-lr0.001-cv.csv
No. 6 file: model-07-keras-embedding-cv.csv
No. 7 file: model-08-keras-search-long-cv.csv
No. 8 file: model-09-lgb-feats-selection-75-cv.csv
No. 9 file: model-10-lgb-feats-selection-75-lr-0.001-cv.csv
No. 10 file: model-11-rf-cv.csv
No. 11 file: model-12-predict-keras-search-prelu-cv.csv
No. 12 file: model-13-predict-keras-he_uni-cv.csv
No. 13 file: model-14-lgb-feats-selection-75-lr-0.001-rand-cv.csv
No. 14 file: model-15-lgb-feats-selection-75-lr-0.001-rand323-cv.csv
No. 15 file: model-16-lgb-feats-selection-68-lr-0.001-mix5-cv.csv
No. 16 file: model-17-lgb-feats-selection-70-lr-0.001-mix5-cv.csv
No. 17 file: model-18-lgb-feats-selection-70-lr-0.001-p5-cv.csv
No. 18 file: model-19-lgb-search-bins-lr-0.0005-cv.csv
No. 19 file: model-20-lgb-lr-0.0008-mix5-cv.csv
No. 20 file: model-21-lgb-wo-per-area-long-cv.csv
No. 21 file: model-22-lgb-wo-per-area-long-2-cv.csv

In [11]:
cv['log_total_price'] = np.log1p(cv['total_price'])
cv['log_parea_total_price'] = np.log1p( cv['total_price'] / cv['building_area'] )

print('Test predictions:')
for i, idx in enumerate(idx_models):
    f = files_test_kf[idx] if idx in use_test_kfold else files_test_one[idx]
    print('No. {} file: {}'.format(i, f))
    df = pd.read_csv('output/'+f)

    test_pred = pd.merge(test_pred, df[['building_id','total_price']], on='building_id')
        
    test_pred = test_pred.rename(columns = {'total_price': 'pred_{}'.format(idx)})
    test_pred[f'log_pred_{idx}'] = np.log1p(test_pred[f'pred_{idx}'])
    test_pred[f'log_parea_pred_{idx}'] = np.log1p( test_pred[f'pred_{idx}'] / test_pred['building_area'] )

Test predictions:
No. 0 file: model-01-lgb-test-one.csv
No. 1 file: model-02-keras-search-test-kfold.csv
No. 2 file: model-03-lgb-feats-selection-test-one.csv
No. 3 file: model-04-lgb-PCA-test-one.csv
No. 4 file: model-05-lgb-wo-per-area-test-one.csv
No. 5 file: model-06-lgb-lr0.001-test-one.csv
No. 6 file: model-07-keras-embedding-test-kfold.csv
No. 7 file: model-08-keras-search-long-test-kfold.csv
No. 8 file: model-09-lgb-feats-selection-75-test-one.csv
No. 9 file: model-10-lgb-feats-selection-75-lr-0.001-test-one.csv
No. 10 file: model-11-rf-test-one.csv
No. 11 file: model-12-predict-keras-search-prelu-test-kfold.csv
No. 12 file: model-13-predict-keras-he_uni-test-kfold.csv
No. 13 file: model-14-lgb-feats-selection-75-lr-0.001-rand-test-one.csv
No. 14 file: model-15-lgb-feats-selection-75-lr-0.001-rand323-test-one.csv
No. 15 file: model-16-lgb-feats-selection-68-lr-0.001-mix5-test-one.csv
No. 16 file: model-17-lgb-feats-selection-70-lr-0.001-mix5-test-one.csv
No. 17 file: model-18-lgb-feats-selection-70-lr-0.001-p5-test-one.csv
No. 18 file: model-19-lgb-search-bins-lr-0.0005-test-one.csv
No. 19 file: model-20-lgb-lr-0.0008-mix5-test-one.csv
No. 20 file: model-21-lgb-wo-per-area-long-test-one.csv
No. 21 file: model-22-lgb-wo-per-area-long-2-test-one.csv

In [12]:
display(cv.head())
display(test_pred.head())

if is_per_area:
    cols_pred = [f'log_parea_pred_{idx}' for idx in idx_models]
else:
    cols_pred = [f'log_pred_{idx}' for idx in idx_models]

,building_id,building_area,total_price,pred_1,log_pred_1,log_parea_pred_1,pred_2,log_pred_2,log_parea_pred_2,pred_3,...,log_pred_20,log_parea_pred_20,pred_21,log_pred_21,log_parea_pred_21,pred_22,log_pred_22,log_parea_pred_22,log_total_price,log_parea_total_price
0,e3mMIMR3JJqCaXz1,3.418175,6.476038e+05,6.331552e+05,13.358472,12.129369,717209.94,13.483125,12.254022,6.656891e+05,...,13.367018,12.137915,6.959114e+05,13.452979,12.223876,6.949261e+05,13.451562,12.222459,13.381036,12.151933
1,LgwzgklNvy4QCtq5,4.041309,3.321452e+06,3.064324e+06,14.935338,13.538770,2899842.20,14.880167,13.483600,3.079196e+06,...,14.969561,13.572994,3.125225e+06,14.955017,13.558450,3.130663e+06,14.956756,13.560188,15.015913,13.619345
2,ucIR2NLLsC3T650L,5.584279,9.570885e+06,9.827776e+06,16.100723,14.380769,9766813.00,16.094501,14.374546,9.814852e+06,...,16.098194,14.378239,9.883518e+06,16.106379,14.386424,9.911790e+06,16.109236,14.389281,16.074236,14.354282
3,jre1pJhcQj91Kdky,13.563031,1.421501e+07,1.255350e+07,16.345510,13.738164,12699800.00,16.357097,13.749750,1.255981e+07,...,16.354260,13.746914,1.282443e+07,16.366863,13.759516,1.279904e+07,16.364881,13.757534,16.469809,13.862462
4,rQpYpY9nRG7X5mmr,4.688108,7.627120e+05,1.215194e+06,14.010415,12.465389,2012610.50,14.514944,12.969916,1.128419e+06,...,13.933257,12.388231,1.236214e+06,14.027565,12.482539,1.239269e+06,14.030033,12.485007,13.544637,11.999613

,building_id,building_area,pred_1,log_pred_1,log_parea_pred_1,pred_2,log_pred_2,log_parea_pred_2,pred_3,log_pred_3,...,log_parea_pred_19,pred_20,log_pred_20,log_parea_pred_20,pred_21,log_pred_21,log_parea_pred_21,pred_22,log_pred_22,log_parea_pred_22
0,X5gsdTWGS3W7JJQB,3.418175,1.526912e+07,16.541343,15.312236,12470072.0,16.338842,15.109735,1.531685e+07,16.544464,...,15.245864,1.478805e+07,16.509330,15.280223,1.237427e+07,16.331130,15.102023,1.201060e+07,16.301300,15.072193
1,BTshNOJyKHnT2YIT,7.726227,3.924241e+06,15.182684,13.138065,3916552.2,15.180723,13.136104,3.977095e+06,15.196062,...,13.134906,3.918591e+06,15.181243,13.136624,3.933908e+06,15.185144,13.140525,3.933533e+06,15.185049,13.140430
2,dhdymr0lV8N5kZOT,12.170581,1.096127e+07,16.209879,13.710858,11912735.0,16.293119,13.794098,1.084967e+07,16.199646,...,13.686933,1.069408e+07,16.185201,13.686181,1.137126e+07,16.246599,13.747579,1.146014e+07,16.254386,13.755365
3,VEwyGGMcD56w5BOc,2.252256,6.155550e+06,15.632865,14.820933,5940670.0,15.597333,14.785400,6.015238e+06,15.609807,...,14.796868,6.033528e+06,15.612843,14.800910,5.784739e+06,15.570734,14.758802,5.778982e+06,15.569738,14.757806
4,wmUeMoJZfsqaSX9b,5.813985,1.062995e+06,13.876602,12.116340,1088488.1,13.900301,12.140039,1.027248e+06,13.842395,...,12.138313,1.089268e+06,13.901017,12.140755,1.010440e+06,13.825898,12.065636,9.995482e+05,13.815060,12.054798

### Check models scores

In [13]:
for i, idx_model in enumerate(idx_models):
    print('%2d'%i, 'model-%02d'%idx_model, '%.6f'%cal_score(cv['total_price'], cv[f'pred_{idx_model}']))

 0 model-01 5870.873059
 1 model-02 5400.852164
 2 model-03 5877.873452
 3 model-04 5713.867808
 4 model-05 5724.869598
 5 model-06 5886.873769
 6 model-07 5171.836449
 7 model-08 5514.858826
 8 model-09 5872.873118
 9 model-10 5897.873845
10 model-11 5075.838018
11 model-12 5486.856963
12 model-13 5506.858055
13 model-14 5908.873901
14 model-15 5900.873836
15 model-16 5907.874126
16 model-17 5905.874165
17 model-18 5908.874297
18 model-19 5911.874156
19 model-20 5908.874040
20 model-21 5758.870702
21 model-22 5752.870671

## Model training

### Params

In [14]:
is_log_target = True
is_per_area_target = True

map_target = {
    (True, True):   'log_per_area_total_price',
    (True, False):  'log_total_price',
    (False, True):  'per_area_total_price',
    (False, False): 'total_price'
}
col_target = map_target[(is_log_target, is_per_area_target)]

#cols_feats_add = ['encoded_latlon', 'building_per_land_area'] # add feats into model
cols_num_add = [
    'building_per_land_area', 'height_r', #'top_floor',
    # dt num feats
    'day_in_year_txn_dt', 'day_in_year_building_complete_dt', 'dt_diff_building_complete_dt_txn_dt',
    # dt cat feats (??)
    'dow_building_complete_dt', # 'dow_txn_dt', 'month_txn_dt', 'quarter_txn_dt', 'month_building_complete_dt', 
    'quarter_building_complete_dt', 'year_txn_dt', 'year_building_complete_dt'
]
cols_cat_add = ['encoded_latlon']

#cols_feats_rm = [] # TODO: implement before using it

### Processing

In [15]:
def pre_processing(df, cols_num, cols_cat): #, cols_feats
    # Convert types
    df[cols_num] = df[cols_num].astype('float32')
    
    # generate target
    if 'total_price' in df:
        df['total_price'] = df['total_price'].astype('float32')
        df['log_total_price'] = np.log1p(df['total_price'])
        df['per_area_total_price'] = df['total_price'] / df['building_area']
        df['log_per_area_total_price'] = np.log1p(df['per_area_total_price'])
        df['target'] = df[col_target]

    # generate lat/lon encoded
    kmeans = pickle.load(open('./object_kmeans_k6_combined.pkl', 'rb'))
    df['encoded_latlon'] = kmeans.predict(df[['lat','lon']])
    
    # generate dt feats
    df = create_dt_feats(df, 'txn_dt')
    df = create_dt_feats(df, 'building_complete_dt')
    df['dt_diff_building_complete_dt_txn_dt'] = df['txn_dt'] - df['building_complete_dt']
    
    # generate building to land ratio
    df['building_per_land_area'] = df['building_area'] / df['land_area']
 
    #cols_feats = cols_num + cols_cat + cols_feats_add
    
    # fix town and city
    df['town'] = df['city'].astype('str')+'-'+df['town'].astype('str')
    df['village'] = df['town'].astype('str')+'-'+df['village'].astype('str')
    
    # height ratio
    df['height_r'] = df['txn_floor'] / df['total_floor']
    df['top_floor'] = df['txn_floor'] == df['total_floor']
    
    return df  #, cols_feats

from feature_engineering import CategoricalColumnsEncoder
from feature_engineering import TargetMeanEncoding
from feature_engineering import MultiLabelEncoding

class FeatureEngineering():
    def __init__(self, cols_num, cols_cat, cols_feats, col_target, n_ran_encode=4):
        # cols
        self.cols_num = cols_num
        self.cols_cat = cols_cat
        self.cols_feats = cols_feats
        self.col_target = col_target
        
        # Numbers
        self.n_ran_encode = n_ran_encode
        
        # encoders
        #self.tar_encoder = TargetMeanEncoding(col_target = self.col_target)
        #self.ran_encoder = MultiLabelEncoding(self.n_ran_encode)
        self.cat_astyper = CategoricalColumnsEncoder(mode='pandas')
        
    def fit_transform(self, df):
        df = df.copy()    
#        encoded1 = self.tar_encoder.fit_transform(df[self.cols_cat], df[self.col_target])
#        encoded2 = self.ran_encoder.fit_transform(df[self.cols_cat])
        self.cat_astyper.fit_transform(df, self.cols_cat)    
        return df
#        return pd.concat([df, encoded1, encoded2], axis=1)
    
    def transform(self, df):
        df = df.copy()
#        encoded1 = self.tar_encoder.transform(df[self.cols_cat])
#        encoded2 = self.ran_encoder.transform(df[self.cols_cat])     # TODO: add generated feats into cols_feats
        self.cat_astyper.transform(df)
        return df
#        return pd.concat([df, encoded1, encoded2], axis=1)

def post_processing(y_pred, df):
    """Args: 
          y_pred (1d np.array): raw prediction y
          df (pd.Dataframe): input feature df
       Return: np.array
    """
    y_pred_final = y_pred.copy()
    
    if is_log_target:
        y_pred_final = np.expm1(y_pred_final)
        y_pred_final = np.clip(y_pred_final, 0, None)

    if is_per_area_target:
        y_pred_final = y_pred_final * df['building_area'].values
        
    return y_pred_final

### Columns

In [16]:
cols_num = ['txn_dt', 'total_floor', 'building_complete_dt', 'parking_area', 'parking_price', 'txn_floor',
            'land_area', 'building_area', 'lat', 'lon', 'village_income_median', 'town_population', 'town_area',
            'town_population_density', 'doc_rate', 'master_rate', 'bachelor_rate', 'jobschool_rate',
            'highschool_rate', 'junior_rate', 'elementary_rate', 'born_rate', 'death_rate', 'marriage_rate',
            'divorce_rate', 'N_50', 'N_500', 'N_1000', 'N_5000', 'N_10000', 'I_10', 'I_50', 'I_100', 'I_250',
            'I_500', 'I_1000', 'I_5000', 'I_10000', 'I_MIN', 'II_10', 'II_50', 'II_100', 'II_250', 'II_500',
            'II_1000', 'II_5000', 'II_10000', 'II_MIN', 'III_10', 'III_50', 'III_100', 'III_250', 'III_500',
            'III_1000', 'III_5000', 'III_10000', 'III_MIN', 'IV_10', 'IV_50', 'IV_100', 'IV_250', 'IV_500',
            'IV_1000', 'IV_5000', 'IV_10000', 'IV_MIN', 'V_10', 'V_50', 'V_100', 'V_250', 'V_500', 'V_1000',
            'V_5000', 'V_10000', 'V_MIN', 'VI_50', 'VI_100', 'VI_250', 'VI_500', 'VI_1000', 'VI_5000', 'VI_10000',
            'VI_MIN', 'VII_10', 'VII_50', 'VII_100', 'VII_250', 'VII_500', 'VII_1000', 'VII_5000', 'VII_10000',
            'VII_MIN', 'VIII_10', 'VIII_50', 'VIII_100', 'VIII_250', 'VIII_500', 'VIII_1000', 'VIII_5000',
            'VIII_10000', 'VIII_MIN', 'IX_10', 'IX_50', 'IX_100', 'IX_250', 'IX_500', 'IX_1000', 'IX_5000',
            'IX_10000', 'IX_MIN', 'X_10', 'X_50', 'X_100', 'X_250', 'X_500', 'X_1000', 'X_5000', 'X_10000', 'X_MIN',
            'XI_10', 'XI_50', 'XI_100', 'XI_250', 'XI_500', 'XI_1000', 'XI_5000', 'XI_10000', 'XI_MIN', 'XII_10',
            'XII_50', 'XII_100', 'XII_250', 'XII_500', 'XII_1000', 'XII_5000', 'XII_10000', 'XII_MIN', 'XIII_10',
            'XIII_50', 'XIII_100', 'XIII_250', 'XIII_500', 'XIII_1000', 'XIII_5000', 'XIII_10000', 'XIII_MIN',
            'XIV_10', 'XIV_50', 'XIV_100', 'XIV_250', 'XIV_500', 'XIV_1000', 'XIV_5000', 'XIV_10000', 'XIV_MIN']
cols_cat = ['building_material', 'city', 'building_type', 'building_use', 'parking_way', 'town', 'village',
            'I_index_50', 'I_index_500', 'I_index_1000', 'II_index_50', 'II_index_500', 'II_index_1000',
            'III_index_50', 'III_index_500', 'III_index_1000', 'IV_index_50', 'IV_index_500', 'IV_index_1000',
            'IV_index_5000', 'V_index_50', 'V_index_500', 'V_index_1000', 'VI_10', 'VI_index_50', 'VI_index_500',
            'VI_index_1000', 'VII_index_50', 'VII_index_500', 'VII_index_1000', 'VIII_index_50', 'VIII_index_500',
            'VIII_index_1000', 'IX_index_50', 'IX_index_500', 'IX_index_1000', 'IX_index_5000', 'X_index_50',
            'X_index_500', 'X_index_1000', 'XI_index_50', 'XI_index_500', 'XI_index_1000', 'XI_index_5000',
            'XI_index_10000', 'XII_index_50', 'XII_index_500', 'XII_index_1000', 'XIII_index_50', 'XIII_index_500',
            'XIII_index_1000', 'XIII_index_5000', 'XIII_index_10000', 'XIV_index_50', 'XIV_index_500',
            'XIV_index_1000']
cols_feats = cols_num + cols_cat

# informational cols
cols_dt = ['txn_dt', 'building_complete_dt']
cols_bin = ['I_index_50', 'I_index_500', 'I_index_1000', 'II_index_50', 'II_index_500', 'II_index_1000',
            'III_index_50', 'III_index_500', 'III_index_1000', 'IV_index_50', 'IV_index_500', 'IV_index_1000',
            'IV_index_5000', 'V_index_50', 'V_index_500', 'V_index_1000', 'VI_10', 'VI_index_50', 'VI_index_500',
            'VI_index_1000', 'VII_index_50', 'VII_index_500', 'VII_index_1000', 'VIII_index_50', 'VIII_index_500',
            'VIII_index_1000', 'IX_index_50', 'IX_index_500', 'IX_index_1000', 'IX_index_5000', 'X_index_50',
            'X_index_500', 'X_index_1000', 'XI_index_50', 'XI_index_500', 'XI_index_1000', 'XI_index_5000',
            'XI_index_10000', 'XII_index_50', 'XII_index_500', 'XII_index_1000', 'XIII_index_50', 'XIII_index_500',
            'XIII_index_1000', 'XIII_index_5000', 'XIII_index_10000', 'XIV_index_50', 'XIV_index_500',
            'XIV_index_1000']

### Read data

In [17]:
train = pd.read_csv('dataset/train.csv', dtype=object)
test = pd.read_csv('dataset/test.csv', dtype=object)
display(train.head(5))
display(test.head(5))

id_cv = []
for i in range(5):
    id_one_fold = pd.read_csv(f'dataset/id_cv{i}.csv', dtype=object)['building_id']
    id_cv.append(id_one_fold)

,building_id,building_material,city,txn_dt,total_floor,building_type,building_use,building_complete_dt,parking_way,parking_area,...,XIV_500,XIV_index_500,XIV_1000,XIV_index_1000,XIV_5000,XIV_index_5000,XIV_10000,XIV_index_10000,XIV_MIN,total_price
0,e3mMIMR3JJqCaXz1,8,21,18674,4,3,2,6271,2,NaN,...,58,1,157,1,2483,1,6011,1,34.469802848528126,647603.7704719775
1,LgwzgklNvy4QCtq5,8,7,18800,5,1,2,7885,2,NaN,...,28,1,115,1,15872,1,32221,1,40.07357348973039,3321452.0
2,ucIR2NLLsC3T650L,8,7,19289,4,1,2,6028,2,NaN,...,78,1,212,1,15760,1,32228,1,54.46208108983661,9570885.316206373
3,jre1pJhcQj91Kdky,8,21,20385,24,0,2,18325,0,NaN,...,20,1,125,1,2568,1,7271,1,99.62896580763416,14215011.127100045
4,rQpYpY9nRG7X5mmr,1,21,20657,2,4,2,6880,2,NaN,...,18,1,47,1,2587,1,7442,1,124.1312362968124,762711.9757135696

,building_id,building_material,city,txn_dt,total_floor,building_type,building_use,building_complete_dt,parking_way,parking_area,...,XIV_250,XIV_500,XIV_index_500,XIV_1000,XIV_index_1000,XIV_5000,XIV_index_5000,XIV_10000,XIV_index_10000,XIV_MIN
0,X5gsdTWGS3W7JJQB,1,13,18634,2,4,2,1857,2,NaN,...,7,21,1,129,1,3991,1,8409,1,105.4622312795739
1,BTshNOJyKHnT2YIT,8,7,20199,10,3,2,16011,2,NaN,...,18,44,1,67,1,1950,1,10725,1,100.81980868401074
2,dhdymr0lV8N5kZOT,8,12,19769,4,4,10,18294,2,NaN,...,0,3,1,35,1,3707,1,19459,1,259.8005430183116
3,VEwyGGMcD56w5BOc,10,7,20479,19,2,0,17837,2,NaN,...,16,60,1,144,1,6487,1,29400,1,22.941906168328487
4,wmUeMoJZfsqaSX9b,8,3,18164,13,0,2,13272,2,NaN,...,4,18,1,76,1,1346,1,3280,1,181.21309507601745

### Bunch of things

In [18]:
train = pre_processing(train, cols_num, cols_cat)
test = pre_processing(test, cols_num, cols_cat)

cols_num = cols_num + [c for c in cols_num_add if c not in cols_num]
cols_cat = cols_cat + [c for c in cols_cat_add if c not in cols_cat]
cols_feats = cols_num + cols_cat

# PARS #
N_feats_rm = 220
# PARS #

from vars_03 import shuffle_results_per_area_new, score_base_per_area_new

feat_imp = pd.DataFrame({'feats': shuffle_results_per_area_new[:,0],
                         'avg':shuffle_results_per_area_new[:,1]})
feat_imp['diff'] = feat_imp['avg'] - score_base_per_area_new
feat_imp = feat_imp.sort_values(by='diff', ascending=False)
print(feat_imp.reset_index().values)

feats_rm = list(feat_imp.iloc[:(N_feats_rm+1)]['feats'].values)
feats_rm.remove('none')
print(len(feats_rm))
print(feats_rm)

# !!!!!!! Merge pred feats and features !!!!!!! #
train = pd.merge(train, cv[['building_id'] + cols_pred], on='building_id', how='left')
test = pd.merge(test, test_pred[['building_id'] + cols_pred], on='building_id', how='left')
cols_num = cols_num + cols_pred
cols_feats = cols_pred # cols_feats
# !!!!!!! Merge pred feats and features !!!!!!! #

print('N feats (before):', len(cols_feats))
cols_feats = list(set(cols_feats) - set(feats_rm))
print('N feats (after):', len(cols_feats))
print(cols_feats)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator KMeans from version 0.20.3 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator KMeans from version 0.20.3 when using version 0.21.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

[[0 'dow_txn_dt' 5626.198099861352 3.999921830412859]
 [1 'X_100' 5623.8648216837755 1.666643652836683]
 [2 'N_500' 5623.86477971246 1.6666016815215698]
 [3 'VI_250' 5623.531524725981 1.3333466950425645]
 [4 'death_rate' 5623.531507556135 1.3333295251959498]
 [5 'elementary_rate' 5623.531436894802 1.3332588638631933]
 [6 'V_50' 5623.198158176917 0.9999801459780429]
 [7 'XI_index_1000' 5622.864846795162 0.6666687642227771]
 [8 'VI_index_500' 5622.8648455873445 0.6666675564056277]
 [9 'XIV_10' 5622.8648405979575 0.6666625670186477]
 [10 'V_10' 5622.864834421419 0.6666563904800569]
 [11 'IV_500' 5622.864750886645 0.666572855706363]
 [12 'IV_250' 5622.864733466064 0.666555435124792]
 [13 'III_5000' 5622.864650842203 0.6664728112646117]
 [14 'month_txn_dt' 5622.531517782187 0.33333975124787685]
 [15 'III_index_50' 5622.531512620851 0.3333345899118285]
 [16 'XIII_index_50' 5622.531512329743 0.33333429880440235]
 [17 'XII_index_50' 5622.531512240729 0.3333342097903369]
 [18 'I_index_1000' 5622.531511732239 0.3333337013000346]
 [19 'X_index_1000' 5622.531511524641 0.33333349370241194]
 [20 'II_index_50' 5622.531511243862 0.3333332129232076]
 [21 'II_10' 5622.531510981692 0.3333329507531744]
 [22 'VI_index_50' 5622.53151084566 0.3333328147209613]
 [23 'XIII_index_1000' 5622.531510471169 0.3333324402301514]
 [24 'XIII_index_10000' 5622.53150999701 0.3333319660714551]
 [25 'XIV_index_50' 5622.53150997178 0.3333319408411626]
 [26 'X_50' 5622.531508278963 0.33333024802414]
 [27 'VII_10' 5622.53150216033 0.3333241293912579]
 [28 'VII_index_500' 5622.198179941119 1.910179889819119e-06]
 [29 'V_index_500' 5622.198178931959 9.010200301418081e-07]
 [30 'III_10' 5622.198178898609 8.676697689224966e-07]
 [31 'X_index_500' 5622.19817869235 6.614109224756248e-07]
 [32 'IX_index_1000' 5622.198178559668 5.287292879074812e-07]
 [33 'quarter_txn_dt' 5622.198178551931 5.209922164794989e-07]
 [34 'I_10' 5622.198178492202 4.612629709299654e-07]
 [35 'III_index_500' 5622.198178454546 4.2360716179246083e-07]
 [36 'XIII_index_5000' 5622.19817836761 3.3667129173409194e-07]
 [37 'XII_index_500' 5622.198178328433 2.974938979605213e-07]
 [38 'VII_index_1000' 5622.198178088682 5.774290912086144e-08]
 [39 'bachelor_rate' 5622.198178072319 4.138018994126469e-08]
 [40 'IX_index_500' 5622.198178059717 2.8778231353498995e-08]
 [41 'month_building_complete_dt' 5622.1981780522765
  2.133765519829467e-08]
 [45 'XI_index_10000' 5622.198178030939 0.0]
 [47 'XIV_index_1000' 5622.198178030939 0.0]
 [46 'XII_index_1000' 5622.198178030939 0.0]
 [42 'none' 5622.198178030939 0.0]
 [44 'IX_index_5000' 5622.198178030939 0.0]
 [43 'top_floor' 5622.198178030939 0.0]
 [48 'XI_index_5000' 5622.1981779963835 -3.4555341699160635e-08]
 [49 'VIII_index_1000' 5622.19817789871 -1.3222870620666072e-07]
 [50 'VI_50' 5622.198177866639 -1.6430021787527949e-07]
 [51 'VI_10' 5622.198177862611 -1.6832746041473e-07]
 [52 'XIV_index_500' 5622.198177806081 -2.2485801309812814e-07]
 [53 'X_10' 5622.198177622675 -4.0826398617355153e-07]
 [54 'III_index_1000' 5622.198177460655 -5.702841008314863e-07]
 [55 'XI_10' 5622.198177453152 -5.777865226264112e-07]
 [56 'XI_index_500' 5622.198177419567 -6.113714334787801e-07]
 [57 'XI_index_50' 5622.198177190167 -8.407714631175622e-07]
 [58 'X_index_50' 5622.198177079342 -9.515970305074006e-07]
 [59 'IV_index_50' 5622.198176894956 -1.1359825293766335e-06]
 [60 'XIII_10' 5622.1981768201995 -1.210739355883561e-06]
 [61 'VII_index_50' 5622.1981768001215 -1.2308173609199002e-06]
 [62 'VIII_index_500' 5622.198176767808 -1.2631307981791906e-06]
 [63 'VIII_index_50' 5622.198176762678 -1.2682612577918917e-06]
 [64 'IV_index_5000' 5622.198176656127 -1.3748122000833973e-06]
 [65 'I_index_50' 5622.198175947634 -2.0833049347857013e-06]
 [66 'VI_100' 5622.198174959748 -3.071190803893842e-06]
 [67 'V_index_50' 5622.198170722363 -7.30857573216781e-06]
 [68 'V_index_1000' 5622.198167331589 -1.0699350241338834e-05]
 [69 'XIII_100' 5622.198166181178 -1.1849760994664393e-05]
 [70 'XI_100' 5622.198159986295 -1.804464409360662e-05]
 [71 'junior_rate' 5622.198141263068 -3.676787127915304e-05]
 [72 'IX_10' 5621.864846037043 -0.3333319938956265]
 [73 'II_index_500' 5621.864844887711 -0.3333331432277191]
 [74 'IV_index_500' 5621.864844812134 -0.33333321880490985]
 [75 'quarter_building_complete_dt' 5621.864844412896 -0.3333336180430706]
 [76 'II_index_1000' 5621.864844077448 -0.33333395349109196]
 [77 'I_50' 5621.864842276172 -0.3333357547671767]
 [78 'I_index_500' 5621.864842193446 -0.3333358374929958]
 [79 'N_5000' 5621.864841746953 -0.33333628398577275]
 [80 'IV_10' 5621.864833796472 -0.3333442344664945]
 [81 'IV_50' 5621.864828957331 -0.3333490736076783]
 [82 'XIII_50' 5621.864828330348 -0.3333497005905883]
 [83 'highschool_rate' 5621.86482539502 -0.3333526359192547]
 [84 'XI_50' 5621.8648246405855 -0.33335339035329525]
 [85 'VI_1000' 5621.864741492146 -0.33343653879273916]
 [86 'IV_index_1000' 5621.531511202432 -0.6666668285070045]
 [87 'VI_index_1000' 5621.531509417956 -0.6666686129829031]
 [88 'XIII_index_500' 5621.531509084193 -0.6666689467456308]
 [89 'IX_index_50' 5621.531508183839 -0.6666698470999108]
 [90 'N_10000' 5621.531482596852 -0.6666954340871598]
 [91 'IX_100' 5621.531387192493 -0.6667908384461043]
 [92 'IX_50' 5621.198168296532 -1.0000097344072856]
 [93 'IV_100' 5621.198167265143 -1.0000107657961053]
 [94 'divorce_rate' 5621.198167083848 -1.0000109470911411]
 [95 'V_100' 5621.198148743951 -1.0000292869881378]
 [96 'VIII_10' 5621.19813018365 -1.0000478472884424]
 [97 'I_100' 5620.864837552042 -1.333340478896389]
 [98 'XIII_250' 5620.8647407297685 -1.3334373011703065]
 [99 'I_250' 5620.531461415718 -1.6667166152210484]
 [100 'III_100' 5620.53145815384 -1.66671987709924]
 [101 'born_rate' 5620.531385941308 -1.6667920896306896]
 [102 'marriage_rate' 5620.53134311472 -1.666834916219159]
 [103 'II_50' 5619.864819097739 -2.3333589331996336]
 [104 'II_100' 5619.864778974959 -2.3333990559794984]
 [105 'XII_10' 5619.531444468317 -2.66673356262163]
 [106 'I_500' 5619.531407450009 -2.666770580929551]
 [107 'XIV_50' 5619.531388782321 -2.6667892486175333]
 [108 'master_rate' 5619.531272692548 -2.6669053383911887]
 [109 'X_250' 5618.864764033228 -3.3334139977105224]
 [110 'XIV_500' 5618.864342534441 -3.333835496498068]
 [111 'N_1000' 5618.5314016435705 -3.6667763873683725]
 [112 'XIV_100' 5618.198078681879 -4.000099349059383]
 [113 'VI_500' 5617.864809473198 -4.333368557740869]
 [114 'X_500' 5617.864726828452 -4.333451202486685]
 [115 'city' 5617.864698539542 -4.333479491397156]
 [116 'XI_500' 5617.864693553082 -4.333484477856473]
 [117 'VIII_10000' 5617.864476874784 -4.333701156155257]
 [118 'year_txn_dt' 5617.198076597517 -5.00010143342206]
 [119 'XII_100' 5616.531285457609 -5.666892573330188]
 [120 'VIII_50' 5616.53116159374 -5.667016437198981]
 [121 'IV_10000' 5616.530933752427 -5.667244278512044]
 [122 'XIII_1000' 5616.197948489258 -6.00022954168071]
 [123 'VII_50' 5615.8646565703775 -6.333521460561315]
 [124 'III_50' 5615.864578851782 -6.333599179156408]
 [125 'XIII_MIN' 5615.863864117387 -6.334313913552251]
 [126 'III_1000' 5615.531154151915 -6.667023879023873]
 [127 'III_250' 5615.197972289937 -7.0002057410019916]
 [128 'day_in_year_txn_dt' 5615.197717352678 -7.000460678260424]
 [129 'I_MIN' 5615.197507615765 -7.000670415173772]
 [130 'XIII_500' 5614.864782368149 -7.333395662790281]
 [131 'VIII_5000' 5614.8644260795345 -7.333751951404338]
 [132 'XI_250' 5614.198012659142 -8.000165371797266]
 [133 'V_500' 5613.864522148127 -8.3336558828114]
 [134 'VII_100' 5612.864621499438 -9.333556531501017]
 [135 'XIV_250' 5612.864507258238 -9.333670772701225]
 [136 'X_10000' 5612.864422917592 -9.333755113347252]
 [137 'IX_250' 5612.197943092059 -10.000234938879657]
 [138 'XII_50' 5611.864716116007 -10.333461914931831]
 [139 'II_250' 5611.531204761585 -10.666973269353548]
 [140 'VIII_100' 5611.197489161718 -11.00068886922054]
 [141 'X_1000' 5611.1974761152305 -11.000701915708305]
 [142 'IV_1000' 5610.197780795169 -12.000397235769924]
 [143 'III_500' 5609.864625882866 -12.333552148073068]
 [144 'XI_5000' 5609.531155381643 -12.667022649296086]
 [145 'IV_5000' 5609.197706033 -13.000471997938803]
 [146 'V_10000' 5608.863958777308 -13.33421925363109]
 [147 'V_1000' 5607.8641919474585 -14.33398608348034]
 [148 'III_10000' 5607.530979468943 -14.667198561995974]
 [149 'dow_building_complete_dt' 5606.197844315274 -16.000333715664965]
 [150 'XII_250' 5605.197587606141 -17.000590424798247]
 [151 'XI_MIN' 5605.197241903549 -17.00093612738965]
 [152 'day_in_year_building_complete_dt' 5604.864328657757
  -17.333849373181692]
 [153 'N_50' 5604.864254293628 -17.333923737311125]
 [154 'II_10000' 5604.197652440472 -18.000525590467078]
 [155 'town_population_density' 5604.197294140048 -18.00088389089069]
 [156 'I_1000' 5603.864588842937 -18.333589188001497]
 [157 'VI_MIN' 5603.53101436155 -18.667163669389083]
 [158 'V_250' 5601.531167299079 -20.66701073185959]
 [159 'XIV_1000' 5601.530968850023 -20.66720918091596]
 [160 'IX_5000' 5601.197334561381 -21.000843469558276]
 [161 'IV_MIN' 5600.530704017255 -21.667474013684114]
 [162 'VIII_250' 5599.530753235061 -22.667424795878105]
 [163 'XII_MIN' 5599.5306437465815 -22.667534284357316]
 [164 'V_MIN' 5599.530577663364 -22.667600367574778]
 [165 'XIV_10000' 5598.86407014491 -23.334107886028505]
 [166 'X_5000' 5598.864031025256 -23.334147005683008]
 [167 'XII_5000' 5598.863995332543 -23.334182698396035]
 [168 'XII_10000' 5598.863356083537 -23.334821947401906]
 [169 'I_5000' 5598.53071497216 -23.667463058778594]
 [170 'XIV_MIN' 5597.86421636445 -24.333961666488904]
 [171 'building_material' 5595.530271387529 -26.66790664340988]
 [172 'V_5000' 5594.530518116678 -27.667659914261094]
 [173 'jobschool_rate' 5593.530484047071 -28.66769398386805]
 [174 'III_MIN' 5592.863624962647 -29.334553068291825]
 [175 'XII_500' 5591.53040742391 -30.667770607028615]
 [176 'year_building_complete_dt' 5589.530696041135 -32.66748198980349]
 [177 'II_500' 5587.863983647695 -34.33419438324381]
 [178 'IX_MIN' 5586.8635834057395 -35.334594625199315]
 [179 'VII_MIN' 5583.863423356696 -38.334754674242504]
 [180 'IX_500' 5582.530697048016 -39.667480982922825]
 [181 'X_MIN' 5578.530269768843 -43.66790826209581]
 [182 'VIII_MIN' 5577.196328425532 -45.00184960540719]
 [183 'II_MIN' 5576.5303291046175 -45.66784892632131]
 [184 'parking_area' 5575.863981489092 -46.33419654184672]
 [185 'VII_250' 5568.863312305902 -53.33486572503716]
 [186 'XI_10000' 5565.196938375314 -57.001239655624886]
 [187 'VIII_500' 5565.196360754413 -57.0018172765258]
 [188 'IX_10000' 5559.863079351134 -62.335098679805014]
 [189 'XII_1000' 5555.861277713025 -66.33690031791411]
 [190 'II_5000' 5554.529612748928 -67.6685652820106]
 [191 'VIII_1000' 5552.528801637586 -69.66937639335265]
 [192 'I_10000' 5552.195918917966 -70.00225911297275]
 [193 'building_use' 5551.863240052596 -70.33493797834308]
 [194 'II_1000' 5550.8632751184 -71.33490291253838]
 [195 'lat' 5548.195735547498 -74.00244248344097]
 [196 'town_area' 5546.863413065827 -75.33476496511139]
 [197 'IX_1000' 5543.529731298494 -78.66844673244486]
 [198 'town_population' 5534.529431426497 -87.66874660444228]
 [199 'XIV_5000' 5530.195400799971 -92.0027772309677]
 [200 'VI_5000' 5529.529661134373 -92.66851689656596]
 [201 'VII_5000' 5489.192328577916 -133.00584945302307]
 [202 'VII_500' 5479.195106489623 -143.00307154131588]
 [203 'dt_diff_building_complete_dt_txn_dt' 5473.527995237918
  -148.670182793021]
 [204 'parking_way' 5414.860609073895 -207.3375689570439]
 [205 'XI_1000' 5413.860127530227 -208.3380505007117]
 [206 'lon' 5359.52438828603 -262.6737897449084]
 [207 'XIII_5000' 5358.859125160594 -263.33905287034486]
 [208 'VII_1000' 5351.525141243876 -270.6730367870632]
 [209 'parking_price' 5347.8579148569925 -274.34026317394637]
 [210 'building_type' 5194.189481779747 -428.0086962511914]
 [211 'building_area' 5141.185881611057 -481.01229641988175]
 [212 'doc_rate' 5066.519451777339 -555.6787262536]
 [213 'height_r' 5062.5160344555725 -559.6821435753664]
 [214 'total_floor' 5059.5205817158485 -562.6775963150903]
 [215 'village_income_median' 5056.850387576144 -565.3477904547944]
 [216 'land_area' 4998.171811431191 -624.0263665997481]
 [217 'VII_10000' 4986.851096755869 -635.3470812750702]
 [218 'building_per_land_area' 4860.836611237709 -761.3615667932299]
 [219 'village' 4520.5029730664755 -1101.6952049644633]
 [220 'VI_10000' 4487.167889170521 -1135.0302888604174]
 [221 'txn_floor' 4484.822064796797 -1137.3761132341415]
 [222 'txn_dt' 3960.1288245917262 -1662.0693534392126]
 [223 'building_complete_dt' 3580.4252353295924 -2041.7729427013464]
 [224 'XIII_10000' 2789.57515375094 -2832.623024279999]
 [225 'town' 1915.9647875459523 -3706.2333904849866]]
220
['dow_txn_dt', 'X_100', 'N_500', 'VI_250', 'death_rate', 'elementary_rate', 'V_50', 'XI_index_1000', 'VI_index_500', 'XIV_10', 'V_10', 'IV_500', 'IV_250', 'III_5000', 'month_txn_dt', 'III_index_50', 'XIII_index_50', 'XII_index_50', 'I_index_1000', 'X_index_1000', 'II_index_50', 'II_10', 'VI_index_50', 'XIII_index_1000', 'XIII_index_10000', 'XIV_index_50', 'X_50', 'VII_10', 'VII_index_500', 'V_index_500', 'III_10', 'X_index_500', 'IX_index_1000', 'quarter_txn_dt', 'I_10', 'III_index_500', 'XIII_index_5000', 'XII_index_500', 'VII_index_1000', 'bachelor_rate', 'IX_index_500', 'month_building_complete_dt', 'XI_index_10000', 'XIV_index_1000', 'XII_index_1000', 'IX_index_5000', 'top_floor', 'XI_index_5000', 'VIII_index_1000', 'VI_50', 'VI_10', 'XIV_index_500', 'X_10', 'III_index_1000', 'XI_10', 'XI_index_500', 'XI_index_50', 'X_index_50', 'IV_index_50', 'XIII_10', 'VII_index_50', 'VIII_index_500', 'VIII_index_50', 'IV_index_5000', 'I_index_50', 'VI_100', 'V_index_50', 'V_index_1000', 'XIII_100', 'XI_100', 'junior_rate', 'IX_10', 'II_index_500', 'IV_index_500', 'quarter_building_complete_dt', 'II_index_1000', 'I_50', 'I_index_500', 'N_5000', 'IV_10', 'IV_50', 'XIII_50', 'highschool_rate', 'XI_50', 'VI_1000', 'IV_index_1000', 'VI_index_1000', 'XIII_index_500', 'IX_index_50', 'N_10000', 'IX_100', 'IX_50', 'IV_100', 'divorce_rate', 'V_100', 'VIII_10', 'I_100', 'XIII_250', 'I_250', 'III_100', 'born_rate', 'marriage_rate', 'II_50', 'II_100', 'XII_10', 'I_500', 'XIV_50', 'master_rate', 'X_250', 'XIV_500', 'N_1000', 'XIV_100', 'VI_500', 'X_500', 'city', 'XI_500', 'VIII_10000', 'year_txn_dt', 'XII_100', 'VIII_50', 'IV_10000', 'XIII_1000', 'VII_50', 'III_50', 'XIII_MIN', 'III_1000', 'III_250', 'day_in_year_txn_dt', 'I_MIN', 'XIII_500', 'VIII_5000', 'XI_250', 'V_500', 'VII_100', 'XIV_250', 'X_10000', 'IX_250', 'XII_50', 'II_250', 'VIII_100', 'X_1000', 'IV_1000', 'III_500', 'XI_5000', 'IV_5000', 'V_10000', 'V_1000', 'III_10000', 'dow_building_complete_dt', 'XII_250', 'XI_MIN', 'day_in_year_building_complete_dt', 'N_50', 'II_10000', 'town_population_density', 'I_1000', 'VI_MIN', 'V_250', 'XIV_1000', 'IX_5000', 'IV_MIN', 'VIII_250', 'XII_MIN', 'V_MIN', 'XIV_10000', 'X_5000', 'XII_5000', 'XII_10000', 'I_5000', 'XIV_MIN', 'building_material', 'V_5000', 'jobschool_rate', 'III_MIN', 'XII_500', 'year_building_complete_dt', 'II_500', 'IX_MIN', 'VII_MIN', 'IX_500', 'X_MIN', 'VIII_MIN', 'II_MIN', 'parking_area', 'VII_250', 'XI_10000', 'VIII_500', 'IX_10000', 'XII_1000', 'II_5000', 'VIII_1000', 'I_10000', 'building_use', 'II_1000', 'lat', 'town_area', 'IX_1000', 'town_population', 'XIV_5000', 'VI_5000', 'VII_5000', 'VII_500', 'dt_diff_building_complete_dt_txn_dt', 'parking_way', 'XI_1000', 'lon', 'XIII_5000', 'VII_1000', 'parking_price', 'building_type', 'building_area', 'doc_rate', 'height_r', 'total_floor', 'village_income_median', 'land_area', 'VII_10000', 'building_per_land_area', 'village', 'VI_10000']

N feats (before): 22
N feats (after): 22
['log_parea_pred_15', 'log_parea_pred_20', 'log_parea_pred_9', 'log_parea_pred_7', 'log_parea_pred_6', 'log_parea_pred_22', 'log_parea_pred_5', 'log_parea_pred_11', 'log_parea_pred_21', 'log_parea_pred_2', 'log_parea_pred_3', 'log_parea_pred_19', 'log_parea_pred_16', 'log_parea_pred_12', 'log_parea_pred_10', 'log_parea_pred_1', 'log_parea_pred_13', 'log_parea_pred_8', 'log_parea_pred_17', 'log_parea_pred_18', 'log_parea_pred_4', 'log_parea_pred_14']

### Train models - kfold

In [19]:
# params
# parameters from model 10: 24, 300, 0.5, 10, 0.1, 0.0
# parameters from model 5: 24, 258, 0.4, 6, 0.04, 0.02
params = {'task': 'train',
          'boosting_type': 'goss',
          'objective': 'mse',
          'metric': 'mape',
          'learning_rate': 0.0001, # 0.001
          'max_depth': 24,
          'num_leaves': 64,  # 300        # may reduce in dim-reduction exp
          'feature_fraction': 1.,
          'min_data_in_leaf': 10,
          'lambda_l1': 0.05,
          'lambda_l2': 0.001,
          'max_bin': 383,
#          'min_sum_hessian_in_leaf': 0.0001,
          'seed': 717,
         }

lgb_other_params = {'num_boost_round': 100000,
                    'verbose_eval': 2000,
                    'early_stopping_rounds': 1000,}

t0 = time.time()

predicts_val = []
predicts_test = test[['building_id']].copy()
best_iterations = []
scores = []
for i, id_fold in enumerate(id_cv):
    #id_fold = id_fold['building_id']
    # split train, val
    df_train = train.loc[~train['building_id'].isin(id_fold)].copy()
    df_val = train.loc[train['building_id'].isin(id_fold)].copy()
    df_test = test.copy()
    
    # feat eng
    feat_eng = FeatureEngineering(cols_num, cols_cat, cols_feats, col_target)
    df_train = feat_eng.fit_transform(df_train)
    df_val = feat_eng.transform(df_val)
    df_test = feat_eng.transform(df_test)

    # Construct lgb dataset
    lgb_train = lgb.Dataset(df_train[cols_feats], df_train[col_target]).construct()
    lgb_val = lgb.Dataset(df_val[cols_feats], df_val[col_target], reference=lgb_train).construct()
        
    # train model    
    model = lgb.train(params, lgb_train, valid_sets=lgb_val, **lgb_other_params, keep_training_booster=True)
    best_iterations.append(model.best_iteration)

    # Predict on val set
    y_pred = model.predict(df_val[cols_feats])
    mse = mean_squared_error(df_val[col_target], y_pred)
    mae = mean_absolute_error(df_val[col_target], y_pred)
    mape = cal_mape(df_val[col_target], y_pred)
    
    y_pred_final = post_processing(y_pred, df_val)
    score = cal_score(df_val['total_price'], y_pred_final)
    scores.append(score)

    print('(Fold %d) score, mse, mae, mape: %.5f, %.5f, %.5f, %.5f.' % (i, score, mse, mae, mape))
    predicts_val.append(pd.DataFrame({'building_id': df_val['building_id'],
                                      'total_price': df_val['total_price'],
                                      'total_price_predict': y_pred_final}))

    # Predict on test set
    y_pred_test = model.predict(df_test[cols_feats])
    predicts_test['target_{}'.format(i)] = y_pred_test
    
print('Total run time:', time.time() - t0)
print('Kfold cv score (mean, stdev, all):', np.mean(scores), np.std(scores), scores) # 5868.87314
mapes = np.mod(scores, 1)
print('Kfold cv mape (mean, stdev, all):', np.mean(mapes), np.std(mapes), mapes)

Training until validation scores don't improve for 1000 rounds.
[2000]	valid_0's mape: 0.0491916
[4000]	valid_0's mape: 0.0407054
[6000]	valid_0's mape: 0.0338288
[8000]	valid_0's mape: 0.0282748
[10000]	valid_0's mape: 0.0238298
[12000]	valid_0's mape: 0.016115
[14000]	valid_0's mape: 0.0133696
[16000]	valid_0's mape: 0.0118676
[18000]	valid_0's mape: 0.010988
[20000]	valid_0's mape: 0.0104439
[22000]	valid_0's mape: 0.0100475
[24000]	valid_0's mape: 0.00976101
[26000]	valid_0's mape: 0.00954608
[28000]	valid_0's mape: 0.00939166
[30000]	valid_0's mape: 0.00929383
[32000]	valid_0's mape: 0.00923243
[34000]	valid_0's mape: 0.00920313
[36000]	valid_0's mape: 0.00919033
[38000]	valid_0's mape: 0.00918408
[40000]	valid_0's mape: 0.00918185
Early stopping, best iteration is:
[39487]	valid_0's mape: 0.00918137
(Fold 0) score, mse, mae, mape: 5849.87369, 0.03670, 0.12197, 0.00918.
Training until validation scores don't improve for 1000 rounds.
[2000]	valid_0's mape: 0.0492625
[4000]	valid_0's mape: 0.0408073
[6000]	valid_0's mape: 0.0339528
[8000]	valid_0's mape: 0.0284161
[10000]	valid_0's mape: 0.0239786
[12000]	valid_0's mape: 0.0162018
[14000]	valid_0's mape: 0.0134461
[16000]	valid_0's mape: 0.011928
[18000]	valid_0's mape: 0.0110511
[20000]	valid_0's mape: 0.0105072
[22000]	valid_0's mape: 0.0101003
[24000]	valid_0's mape: 0.00981272
[26000]	valid_0's mape: 0.00959754
[28000]	valid_0's mape: 0.00944133
[30000]	valid_0's mape: 0.00933627
[32000]	valid_0's mape: 0.00927115
[34000]	valid_0's mape: 0.00923809
[36000]	valid_0's mape: 0.00922399
[38000]	valid_0's mape: 0.00921788
Early stopping, best iteration is:
[37920]	valid_0's mape: 0.00921518
(Fold 1) score, mse, mae, mape: 5893.87291, 0.03821, 0.12275, 0.00922.
Training until validation scores don't improve for 1000 rounds.
[2000]	valid_0's mape: 0.0490105
[4000]	valid_0's mape: 0.0405437
[6000]	valid_0's mape: 0.0336907
[8000]	valid_0's mape: 0.0281646
[10000]	valid_0's mape: 0.0237438
[12000]	valid_0's mape: 0.0155864
[14000]	valid_0's mape: 0.0126708
[16000]	valid_0's mape: 0.0114657
[18000]	valid_0's mape: 0.0107515
[20000]	valid_0's mape: 0.0102811
[22000]	valid_0's mape: 0.00993068
[24000]	valid_0's mape: 0.00968476
[26000]	valid_0's mape: 0.00950002
[28000]	valid_0's mape: 0.00937285
[30000]	valid_0's mape: 0.0093043
[32000]	valid_0's mape: 0.00926281
[34000]	valid_0's mape: 0.00924758
[36000]	valid_0's mape: 0.00923883
[38000]	valid_0's mape: 0.00923664
Early stopping, best iteration is:
[37656]	valid_0's mape: 0.00923365
(Fold 2) score, mse, mae, mape: 5906.86953, 0.03885, 0.12266, 0.00923.
Training until validation scores don't improve for 1000 rounds.
[2000]	valid_0's mape: 0.0495324
[4000]	valid_0's mape: 0.0409317
[6000]	valid_0's mape: 0.0339782
[8000]	valid_0's mape: 0.0283783
[10000]	valid_0's mape: 0.0238904
[12000]	valid_0's mape: 0.0160745
[14000]	valid_0's mape: 0.0133625
[16000]	valid_0's mape: 0.0118778
[18000]	valid_0's mape: 0.0110158
[20000]	valid_0's mape: 0.0104978
[22000]	valid_0's mape: 0.0101022
[24000]	valid_0's mape: 0.00981997
[26000]	valid_0's mape: 0.00961329
[28000]	valid_0's mape: 0.00945843
[30000]	valid_0's mape: 0.00935802
[32000]	valid_0's mape: 0.00929951
[34000]	valid_0's mape: 0.00927033
[36000]	valid_0's mape: 0.00925684
[38000]	valid_0's mape: 0.0092517
Early stopping, best iteration is:
[38499]	valid_0's mape: 0.00924997
(Fold 3) score, mse, mae, mape: 5863.87312, 0.03747, 0.12305, 0.00925.
Training until validation scores don't improve for 1000 rounds.
[2000]	valid_0's mape: 0.0494783
[4000]	valid_0's mape: 0.0409379
[6000]	valid_0's mape: 0.0340277
[8000]	valid_0's mape: 0.0284569
[10000]	valid_0's mape: 0.0239895
[12000]	valid_0's mape: 0.0166538
[14000]	valid_0's mape: 0.0139074
[16000]	valid_0's mape: 0.0122857
[18000]	valid_0's mape: 0.011316
[20000]	valid_0's mape: 0.0107077
[22000]	valid_0's mape: 0.0102546
[24000]	valid_0's mape: 0.00993233
[26000]	valid_0's mape: 0.00969133
[28000]	valid_0's mape: 0.00951105
[30000]	valid_0's mape: 0.00938621
[32000]	valid_0's mape: 0.00929375
[34000]	valid_0's mape: 0.00923858
[36000]	valid_0's mape: 0.00920984
[38000]	valid_0's mape: 0.00919838
[40000]	valid_0's mape: 0.00919466
[42000]	valid_0's mape: 0.00919358
Early stopping, best iteration is:
[41465]	valid_0's mape: 0.00919307
(Fold 4) score, mse, mae, mape: 5845.87058, 0.03738, 0.12222, 0.00919.
Total run time: 783.8644299507141
Kfold cv score (mean, stdev, all): 5872.0719657821 24.218375180699198 [5849.873689368912, 5893.8729135991825, 5906.869525394935, 5863.873116254557, 5845.870584292912]
Kfold cv mape (mean, stdev, all): 0.8719657820998691 0.0016159639528670496 [0.87368937 0.8729136  0.86952539 0.87311625 0.87058429]

In [ ]:
display(predicts_test.head())

# pd.concat(predicts_val, axis=0).to_csv('output/'+model_name+'-cv.csv', index=False)

predicts_test['target_mean'] = \
    predicts_test[['target_'+str(i) for i in range(len(id_cv))]].mean(axis=1)
predicts_test['total_price'] = post_processing(predicts_test['target_mean'].values, df_test)
predicts_test[['building_id', 'total_price']].to_csv('output/'+model_name+'_test_kfold.csv', index=False)

print('Best iterations:', best_iterations)
print('Mean best iterations:', int(np.mean(best_iterations)))

### Train model - one

In [ ]:
lgb_other_params_one = {'num_boost_round': int(np.mean(best_iterations)*1.2),
                        'verbose_eval': 2000,}
lgb_other_params_one

t10 = time.time()

df_train = train.copy()
df_test = test.copy()

# feat eng
feat_eng = FeatureEngineering(cols_num, cols_cat, cols_feats, col_target)
df_train = feat_eng.fit_transform(df_train)
df_test = feat_eng.transform(df_test)

# Construct lgb dataset
lgb_train = lgb.Dataset(df_train[cols_feats], df_train[col_target]).construct()

# train model    
model = lgb.train(params, lgb_train, valid_sets=lgb_train, **lgb_other_params_one, keep_training_booster=True)

y_pred = model.predict(df_test[cols_feats])
y_pred_final = post_processing(y_pred, df_test)

df_test_pred = pd.DataFrame({'building_id': df_test['building_id'], 
                             'total_price': y_pred_final})

t11 = time.time()

display(df_test_pred.head(20))

df_test_pred.to_csv('output/'+model_name+'_test_one.csv', index=False)

print('Total run time:', t11 - t10)