In [18]:
import time
import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold

In [28]:
df = pd.read_csv('train.csv', dtype=object)
df['total_price'] = df['total_price'].astype(float)
df = df.sort_values(by='total_price').reset_index(drop=True)

df['price_level'] = df.index // (df.shape[0] // 5)

In [29]:
df[['total_price','price_level']]

        total_price  price_level
0      2.261495e+05            0
1      2.299748e+05            0
2      2.362753e+05            0
3      2.378646e+05            0
4      2.378646e+05            0
5      2.379956e+05            0
6      2.379988e+05            0
7      2.470484e+05            0
8      2.470484e+05            0
9      2.470484e+05            0
10     2.470484e+05            0
11     2.470484e+05            0
12     2.470682e+05            0
13     2.490229e+05            0
14     2.508902e+05            0
15     2.538324e+05            0
16     2.568258e+05            0
17     2.568258e+05            0
18     2.572727e+05            0
19     2.594608e+05            0
20     2.629636e+05            0
21     2.671627e+05            0
22     2.671627e+05            0
23     2.671627e+05            0
24     2.671627e+05            0
25     2.671627e+05            0
26     2.671712e+05            0
27     2.671712e+05            0
28     2.672618e+05            0
29     2.692946e+05            0
...             ...          ...
59970  1.091819e+09            4
59971  1.091819e+09            4
59972  1.091819e+09            4
59973  1.091819e+09            4
59974  1.091819e+09            4
59975  1.118336e+09            4
59976  1.145063e+09            4
59977  1.172001e+09            4
59978  1.172001e+09            4
59979  1.190981e+09            4
59980  1.190981e+09            4
59981  1.226498e+09            4
59982  1.309777e+09            4
59983  1.309777e+09            4
59984  1.309777e+09            4
59985  1.400595e+09            4
59986  1.423615e+09            4
59987  1.613896e+09            4
59988  1.721746e+09            4
59989  1.783530e+09            4
59990  1.783530e+09            4
59991  1.909385e+09            4
59992  1.973377e+09            4
59993  2.038068e+09            4
59994  2.038068e+09            4
59995  2.169519e+09            4
59996  3.378167e+09            4
59997  3.378167e+09            4
59998  4.357039e+09            4
59999  5.088279e+09            4

[60000 rows x 2 columns]

In [33]:
kfold = StratifiedKFold(n_splits=5, shuffle=True)
i = 0
for train_index, test_index in kfold.split(np.zeros(df.shape[0]), df['price_level']):
    val = df.loc[test_index]
    print(val['price_level'].value_counts())
    print(val['total_price'].sum())
    val[['building_id']].to_csv(f'id_cv{i}.csv',index=False)
    i += 1

4    2400
3    2400
2    2400
1    2400
0    2400
Name: price_level, dtype: int64
151633999422.87082
4    2400
3    2400
2    2400
1    2400
0    2400
Name: price_level, dtype: int64
157274675608.022
4    2400
3    2400
2    2400
1    2400
0    2400
Name: price_level, dtype: int64
163160973637.6234
4    2400
3    2400
2    2400
1    2400
0    2400
Name: price_level, dtype: int64
149718436685.60498
4    2400
3    2400
2    2400
1    2400
0    2400
Name: price_level, dtype: int64
154448163238.30176

In [16]:
df['building_id'].nunique()

60000